### ISSUE TITLE
Convert templates from Handlebars to AWTemplate.fromDOM();

### ISSUE THREAD

**Issue by adambezemek** [XCentium/Andersen#7]
Remove `handlebars-latest.js` from `/xc-temp` and `_DesignTool2.html`

Convert the current handlebars templates in the DOM to use Andersen’s custom template system (`AWTemplate`) instead of handlebars.

**Comment by AdamMornes** [comment]
Completed with commit [https://github.com/XCentium/Andersen/commit/e1b2e101fe0538c58528156d02c29f2d37c73d3f](url)
