### ISSUE TITLE
“Tell me more” modals

### ISSUE THREAD

**Issue by adambezemek** [XCentium/Andersen#8]
Replicate the “Tell me more” Modal - design and functionality that was not in InVision.

Use the [Help Me Choose](https://www.andersenwindows.com/windows-and-doors/your-perfect-match/#cs=2&s:0=undefined&s:1=45e238f9-674d-4578-b290-2f17af5f5666&s:2=997ea3b9-f444-42d6-9bf1-26dbd0b576ca) module  for reference.

**Note:** mobile images are in a carousel and desktop images are in grid-like layout.

**Comment by snirankari** [comment]
Completed - https://github.com/XCentium/Andersen/pull/13
